name: minions-bundles-finance-workspace
description: Financial tracking bundle — budgets, expenses, invoices
tier: idea
lane: minions
priority: medium
oss: true
stack: [typescript]
repo: "https://github.com/mxn2020/minions-bundles-finance"
deploy_url: null
last_active: 2026-02-25
tags: []
notes: 
